# This file contains configuration flags to customize your site
theme: jekyll-theme-cayman
title: Euregio Data Science Hub
description: The one stop shop for all Data Science related happenings in the region.

show_downloads: false



